<!--#include virtual="/include/templates/top.asa"-->
<!--#include virtual="/include/menus/wildland.asa"-->
<table cellpadding="5" cellspacing="0" border="0" width="98%">
	<tr>
		<td colspan="10" vAlign="top" class="PageTitle">Deployments</td>
	</tr>	
	<tr>
		<td colspan="10" vAlign="top" class="Content">When a firefighter completes the required wildland training and obtains his or her Incident Qualification Card, they are eligible to be deployed on a wildland fire crew to major forest fires across the United States. The deployments typically occur during July, August, and September and can last for 14 days plus travel time.
		<br><br>
		</td>
				
	</tr>
	<tr>
		<td colspan="7" vAlign="top" class="Content">Under a cooperative agreement with the Missouri Department of Conservation, firefighters are entered into the National Interagency Coordination Center system located in Boise, Idaho and dispatched to blazes as the need arises.  Since the creation of Boone County=s wildland fire team in 1988, members have found themselves spending the summer months battling forest fires in Idaho, Montana, Utah, Oregon, Florida and, of course, on the Mark Twain National Forest in Missouri.
		<br><br>
		</td>
		<td align="right" colspan="3" vAlign="top">
		<img valign="top" border="3" SRC="/images/wildland/deployment/161.jpg"><br>
	    <table width="188">
		<tr>
		<td vAlign="top" class="Caption">
		Wildland team deployments are for two weeks.
	    </td>
	    </tr>
	    </table>
		</td>
	</tr>
	<tr>
		<td colspan="10" vAlign="top" class="Content">Typically, Fire District staff monitors daily fire and resource reports generated by the National Interagency Coordination Center and, from those reports, can anticipate when Boone County&#146;s crew may be activated.  Upon formal activation orders, the crew generally has approximately 6-8 hours to arrive at a staging area in St. Louis.  From there, they are transported to Lambert Airport where they board a chartered aircraft and depart to Boise.  Upon arrival in Boise, they are assigned to a fire or a fire complex (large group of fires).  They are transported to their assignment by bus, fixed-wing aircraft or helicopter.  While on assignment, all expenses are covered and the U.S. Forest Service provides hourly pay.  Additionally, firefighters are protected by federal worker&#146;s compensation insurance.
		<br><br>
		</td>
	</tr>
	<tr>
		<td colspan="10" vAlign="top" class="Content">It is important to note that, without the support and understanding of these volunteer firefighters&#146; families and employers, this effort would not be possible.
		<br><br>
		</td>
	</tr>
	<tr>
	  <td></td>
	  <td></td>
	  <td></td>
	  <td></td>
	  <td></td>
	  <td></td>
	  <td></td>
	  <td></td>
	  <td></td>
	  <td></td>
	</tr>
</table>

<!--#include virtual="/include/templates/bottom.asa"-->
